### ISSUE TITLE
Overshields Addon is not working with Easy Frames addon anymore, any chance fixing it?

### ISSUE THREAD

**Issue by FleXFtw** [enthh/overshields#1]
I really really like this addon, and it makes tanking with blood dk way easier (for me at least), on the party frames I can still track shields, but on my player frame it does not show up. 
![overshields](https://github.com/enthh/overshields/assets/52858964/99d8a520-6b5b-4df5-90d8-0d47940352be)
 I had to dowload a crappy WA to see if i have shield or not but it looks way way worse then Overshields.

**Comment by enthh** [comment]
Overshields is specialized for the Blizzard UI frames - specifically the CompactUnitFrame code. If it was working with Easy Frames earlier, but not now, then maybe Easy Frames is no longer using the CompactUnitFrame code?

I am maintaining this AddOn for CurseForge distribution, and heard about it from the TitanForge podcast. I think I recall that this AddOn was ported to WeakAuras. Maybe it's a matter of digging around a bit more to find the WA port?

I don't have plans to adapt this AddOn to support different unit frames. Sorry.

**Comment by Bodify** [comment]
@enthh There was some changes to the unit frames code in 10.2.5 and it has not been working since then. The compact unit frames still work but player target and focus are bricked atm. This is the same reason it won't work for EasyFrames. I tried having a look but I am not experienced enough and had a hard time trying to figure it out. 
Idk how to link properly but changes are in UnitFrame.lua [here](https://github.com/Gethe/wow-ui-source/commit/45cb43fde1273ac34a6238cd5c1a377013067049#diff-24da1f0a023f321f4d6ca819dd5e3da14a9f853fb911b6450a94ff2cf60e6a1d)
